### ISSUE TITLE
Startup exception on raspberry pi

### ISSUE THREAD

**Issue by 80er** [ElectronNET/Electron.NET#116]
Hi,

followed the sample and created an empty ASP.NET Core project. Building the app on my Win10 machine works fine. 
When i generate the package for my Raspberry PI with the command 
``
dotnet electronize build /target linux /electron-arch armv7l
``
i get the exception below. Electron 1.7.11 is installed on the raspi, node is 8.11.1 (as on my Win10 machine). Already tried an npm install in the resources/app directory on the raspi. 

Uncaught Exception:
Error: spawn EACCES
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at exports.spawn (child_process.js:390:9)
    at portfinder (/home/pi/MediaCenterFrontend/resources/app/main.js:52:22)
    at listen (/home/pi/MediaCenterFrontend/resources/app/node_modules/detect-port/lib/detect-port.js:69:11)
    at Server.server.listen (/home/pi/MediaCenterFrontend/resources/app/node_modules/detect-port/lib/detect-port.js:93:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitListeningNT (net.js:1290:10)

**Comment by GregorBiswanger** [comment]
`EACCES ` means most probably that current user has no rights to execute the electron file.

I hope my answer helps you.

**Comment by 80er** [comment]
Just to make this complete. What i missed is that also used node modules can contain executables (like detect-port). these have to be runable to of course. ;)
