### ISSUE TITLE
"dotnet electronize start"command progress occurs one error "throw errnoException(err, 'spawn');"

### ISSUE THREAD

**Issue by twtyypmb** [ElectronNET/Electron.NET#130]
"dotnet build"and "dotnet electronize init" are ok,but "dotnet electronize start"

the error info is following:
D:\electron.net-api-demos-master\ElectronNET-API-Demos\obj\Host\node_modules\.bin>electron.cmd "..\..\main.js"
internal/child_process.js:323
    throw errnoException(err, 'spawn');
    ^
Error: spawn UNKNOWN
    at _errnoException (util.js:992:11)
    at ChildProcess.spawn (internal/child_process.js:323:11)
    at Object.exports.spawn (child_process.js:502:9)
    at Object.<anonymous> (D:\electron.net-api-demos-master\ElectronNET-API-Demos\obj\Host\node_modules\electron\cli.js:7:18)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

My environment：
os :win 7u32 sp1
vscode:VSCodeSetup-ia32-1.23.1
.net core:dotnet-sdk-2.1.200-win-x86
node version:v8.11.2
electron version:v2.0.1
electrionnet version:0.0.9
application:electron.net-api-demos

**Comment by robertmuehsig** [comment]
It seems we are not compatible with .NET Core 2.1. I will take a look this week.

**Comment by twtyypmb** [comment]
the error does not occure in win7p64，i guess the reason is x86 or x64 environment?

**Comment by twtyypmb** [comment]
@robertmuehsig i have tested with .net core 2.0.0,and the error still occured

**Comment by dongfo** [comment]
the same problem and my devlop machine :win10 64.
vs2017 15.7.2
nodejs V8.11.2

**Comment by tomiscw** [comment]
I get this too on .NET Core 2.0. Win 10 Pro, v1803, 1734.48.

**Comment by GregorBiswanger** [comment]
Hello @twtyypmb and @dongfo,
do you still have the problem or can find a solution?

Best,
Gregor

**Comment by scout208** [comment]
Hi, I am having this issue on Windows IoT Core on Raspberry Pi.
