### ISSUE TITLE
Exception when dotnet electronize build

### ISSUE THREAD

**Issue by ernestotw85** [ElectronNET/Electron.NET#145]
I am trying to run dotnet electronize build and Electron.NET is getting this exception:

Build Electron Application...

Unhandled Exception: System.AggregateException: One or more errors occurred. (The given key was not present in the dictionary.) ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ElectronNET.CLI.Commands.BuildCommand.<ExecuteAsync>b__13_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ElectronNET.CLI.Program.Main(String[] args)

I am using the following versions:;

dotnet --version: 2.1.4
node --version: v9.3.0
dotnet electronize version: 0.0.9.0

**Comment by Elctro** [comment]
Try to install `npm install electron-packager -g` manually.

I had same error and made it work with 
`node` v8.11.3
`npm` 6.1.0
electron-packager `12.1.0` 
electronize 0.0.9.0

**Comment by ernestotw85** [comment]
@Elctro Thank you very much!! I installed all those tools and versions. From cmd I runned this command:
dotnet electronize build  /target win
This command generate a folder with some js, dlls and other files. But my question is Where is located the .exe that show the Electron UI?

**Comment by GregorBiswanger** [comment]
@ernestotw85 the binary file is in "bin/desktop" folder.
