### ISSUE TITLE
Javascript Error; missing \electron.manifest.js

### ISSUE THREAD

**Issue by mblackbourne** [ElectronNET/Electron.NET#205]
Hello all! 

system::
win10
node -11.6.0
dotnet-2.1.401
Solution built in 2.1
Using version 0.11 IAW github Readme

Here is an issue I don't see a direct solution for solution :

I have tried to build the app to see if the error goes away The error to the build win follows the Javascript error. "'Error: Cannot find module 'C:\Users\root\source\repos\WebApplication3\obj\Host\bin\electron.manifest.json'"  

It does not seem like any of the files listed in the error exist; good reason to throw an error ;). 

`C:\Users\root\source\repos\WebApplication3\obj\Host\node_modules\.bin>electron.cmd "..\..\main.js"
App threw an error during load
Error: Cannot find module 'C:\Users\root\source\repos\WebApplication3\obj\Host\bin\electron.manifest.json'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Function.Module._resolveFilename (C:\Users\root\source\repos\WebApplication3\obj\Host\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (internal/modules/cjs/loader.js:528:25)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\root\source\repos\WebApplication3\obj\Host\main.js:13:26)
    at Object.<anonymous> (C:\Users\root\source\repos\WebApplication3\obj\Host\main.js:117:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
PS C:\Users\root\source\repos\WebApplication3> ^C`

Error code for the build: 
`PS C:\Users\root\source\repos\WebApplication3> electronize.exe build win
Build Electron Application...

Unhandled Exception: System.AggregateException: One or more errors occurred. (The given key 'target' was not present in the dictionary.) ---> System.Collections.Generic.KeyNotFoundException: The given key 'target' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ElectronNET.CLI.Commands.BuildCommand.<ExecuteAsync>b__13_0() in D:\Code\GitHub\Electron.NET\ElectronNET.CLI\Commands\BuildCommand.cs:line 45
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ElectronNET.CLI.Program.Main(String[] args) in D:\Code\GitHub\Electron.NET\ElectronNET.CLI\Program.cs:line 54
PS C:\Users\root\source\repos\WebApplication3> `

Thank you!

**Comment by mblackbourne** [comment]
A solution that seems to be working at the moment was to copy the manifest in my application "home" folder, into the /bin/obj dir. 

Did I miss a step in the install?

**Comment by robertmuehsig** [comment]
You need to install invoke the init command like this:

        electronize init

This should create the needed manifest file.

**Comment by ArunEdathadan** [comment]
Run it in visual studio code, it works.

**Comment by amigax** [comment]
any fix for this? i already did init, same issue

**Comment by LapinskasL** [comment]
Having the same issue.
