### ISSUE TITLE
Mac Build doesn't run with cannot find module error.

### ISSUE THREAD

**Issue by ajayplutus** [ElectronNET/Electron.NET#383]
Hello,

I've created demo desktop application with asp.net core 2.2 on mac machine. I've created a build for mac os. I've got the issues on run the build :
Uncaught Exception:
Error: Cannot find module '/Applications/electron.net.host.app/Contents/Resources/bin/electron.manifest.json'
Require stack:
- /Applications/electron.net.host.app/Contents/Resources/app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7552:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/Applications/electron.net.host.app/Contents/Resources/app.asar/main.js:20:26)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)

**Comment by GregorBiswanger** [comment]
did you execute the `electronize init` command in your project?

**Comment by ajayplutus** [comment]
Hi Gregor,

Thanks for reply.

I have already done this then I have created a build. After your reply I have type it again as shown below:

> - Test: demo mac$ electronize init
> - Adding our config file to your project...
> - Config file already in your project.

**Comment by GregorBiswanger** [comment]
@robertmuehsig can you please test it with your mac.

**Comment by ajayplutus** [comment]
Hi @GregorBiswanger, I think @robertmuehsig has not responded since August 2019, can you please check with him and reply as soon as possible.

Thanks In advance.

**Comment by GregorBiswanger** [comment]
unfortunately I don't have a mac to test it.. Robert is currently very busy with his family.. but please try to get help from the community, if no one answers there, please let me know again.. 
https://gitter.im/ElectronNET/community

if you have solved your problem please let me know and close the issue

**Comment by ajayplutus** [comment]
Hi @GregorBiswanger , 
Thanks for reply :)

I've created new web application and created build successfully.
