### ISSUE TITLE
Hi i am trying to build the application for the 32 bit version and i still receive the error

### ISSUE THREAD

**Issue by yannisraft** [ElectronNET/Electron.NET#439]
Hi i am trying to build the application for the 32 bit version and i still receive the error

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.
)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ElectronNET.CLI.Commands.Actions.GetTargetPlatformInformation.Do(String desiredPlatform, String specifiedPlatfromF
romCustom) in D:\Code\GitHub\Electron.NET\ElectronNET.CLI\Commands\Actions\GetTargetPlatformInformation.cs:line 17
   at ElectronNET.CLI.Commands.BuildCommand.<ExecuteAsync>b__19_0() in D:\Code\GitHub\Electron.NET\ElectronNET.CLI\Comma
nds\BuildCommand.cs:line 77
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executio
nContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executio
nContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ElectronNET.CLI.Program.Main(String[] args) in D:\Code\GitHub\Electron.NET\ElectronNET.CLI\Program.cs:line 59
win32 : The term 'win32' is not recognized as the name of a cmdlet, function, script file, or operable program. Check t
he spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:43
+ electronize build /target custom win7-x86;win32 /dotnet-configuration ...
+                                           ~~~~~
    + CategoryInfo          : ObjectNotFound: (win32:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I am using the electron.NET CLI version 9.31.1 on a Windows 10 machine
I tried to build it using the following command:

`electronize.exe build /target custom win-x86;win /dotnet-configuration Debug /electron-arch ia32`

_Originally posted by @raftopyannis in https://github.com/ElectronNET/Electron.NET/issues/152#issuecomment-647949999_

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
