### ISSUE TITLE
Using Electron.Net with Entity Framework

### ISSUE THREAD

**Issue by NMSaiyed** [ElectronNET/Electron.NET#470]
Hello there,
I have tried to create web(ASP.Net Core 3.1) project with Angular. And used EntityFramework(3.1.5), Microsoft.AspNetCore.Identity.
When I tried to execute this project with **electronize start** I am getting error as below.

 An unhandled exception occurred: Job name "..getProjectMetadata" does not exist.
  See "C:\Users\User-1\AppData\Local\Temp\ng-Mz6O16\angular-errors.log" for further details.
  npm ERR! code ELIFECYCLE
  npm ERR! syscall spawn
  npm ERR! file C:\WINDOWS\system32\cmd.exe
  npm ERR! errno ENOENT
  npm ERR! electron.net_angular@0.0.0 build: `ng build "--prod"`
  npm ERR! spawn ENOENT
  npm ERR!
  npm ERR! Failed at the electron.net_angular@0.0.0 build script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  npm ERR! A complete log of this run can be found in:
  npm ERR!     C:\Users\User-1\AppData\Roaming\npm-cache\_logs\2020-08-15T06_44_42_500Z-debug.log
E:\Demo\Electron.Net_Angular\Electron.Net_Angular\Electron.Net_Angular.csproj(41,5): error MSB3073: The command "npm run build -- --prod" exited with code 1.

**Here is Log File error ::**

[error] Error: Job name "..getProjectMetadata" does not exist.
    at Observable.rxjs_1.Observable [as _subscribe] (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\src\experimental\jobs\simple-scheduler.js:350:23)
    at Observable._trySubscribe (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Observable.js:44:25)
    at Observable.subscribe (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Observable.js:30:22)
    at E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\util\subscribeTo.js:22:31
    at Object.subscribeToResult (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:65:54)
    at SwitchMapSubscriber._next (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:86:26)
    at InnerSubscriber._next (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:66:18)
    at E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\util\subscribeTo.js:17:28
    at Object.subscribeToResult (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\util\subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:65:54)
    at SwitchMapSubscriber._next (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\operators\switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (E:\Demo\Electron.Net_Angular\Electron.Net_Angular\ClientApp\node_modules\@angular-devkit\core\node_modules\rxjs\internal\Subscriber.js:66:18)

Note : Its work fine when I don't use EntityFramework and Microsoft.AspNetCore.Identity.

**Comment by GregorBiswanger** [comment]
In this video you can see how to debug under the hood: [Electron.NET - Contributing Getting Started](https://youtu.be/Po-saU_Z6Ws)
If there is a mistake on our part, you are welcome to submit a pull request.

**Comment by NMSaiyed** [comment]
It's worked.
Actually mistake in my integration.
Closing this issue.
