### ISSUE TITLE
build retry bug

### ISSUE THREAD

**Issue by 312977** [ElectronNET/Electron.NET#515]
9.0.5

* **Version**: 9.0.5

3.1

* **Target**: 
windows 32 x64

Steps to Reproduce:

1.  i use  cmd:  electronize build /target win  ,its a  long time , waiting....    when i  ctrl+c   end of this cmd,
and then a try  electronize build /target win  agin ,i get an error:
i  must  to  reatart computer to fix it.

Build Electron Application...
Build ASP.NET Core App for win-x64...
Unhandled exception. System.AggregateException: One or more errors occurred. (The process cannot access the file '\\?\D:\code\合智项目\ToolCabinet\obj\desktop\win' because it is being used by another process.)
 ---> System.IO.IOException: The process cannot access the file '\\?\D:\code\合智项目\ToolCabinet\obj\desktop\win' because it is being used by another process.
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at System.IO.Directory.Delete(String path, Boolean recursive)
   at ElectronNET.CLI.Commands.BuildCommand.<ExecuteAsync>b__19_0() in C:\_WorkRepos\Electron.NET\ElectronNET.CLI\Commands\BuildCommand.cs:line 88
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ElectronNET.CLI.Program.Main(String[] args) in C:\_WorkRepos\Electron.NET\ElectronNET.CLI\Program.cs:line 59

**Comment by GregorBiswanger** [comment]
🎉🚀 New Electron.NET version 23.6.1 released 🚀🎉

With native Electron 23 and .NET 6 support. Your problem should be fixed here. If you continue to have the problem, please let us know. Please note the correct updating of your API & CLI. Info in the README. Have fun!
