### ISSUE TITLE
Electron.WindowManager.CreateWindowAsync -> NullRef when debugging the ASP.NET core app

### ISSUE THREAD

**Issue by robertmuehsig** [ElectronNET/Electron.NET#8]
```
  public async void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
                app.UseBrowserLink();
            }
            else
            {
                app.UseExceptionHandler("/Error");
            }

            app.UseStaticFiles();

            app.UseMvc(routes =>
            {
                routes.MapRoute(
                    name: "default",
                    template: "{controller}/{action=Index}/{id?}");
            });

            // Open the Electron-Window here
            await Electron.WindowManager.CreateWindowAsync();
        }
```

```
WebApplication6> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
WebApplication6>    at ElectronNET.API.WindowManager.CreateWindowAsync(BrowserWindowOptions options, String loadUrl)
WebApplication6>    at ElectronNET.API.WindowManager.<CreateWindowAsync>d__7.MoveNext()
WebApplication6> --- End of stack trace from previous location where exception was thrown ---
WebApplication6>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication6>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication6>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication6>    at WebApplication6.Startup.<Configure>d__5.MoveNext() in D:\Users\muehsig\Documents\Visual Studio 2017\Projects\WebApplication6\WebApplication6\Startup.cs:line 51
WebApplication6> --- End of stack trace from previous location where exception was thrown ---
WebApplication6>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication6>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
WebApplication6>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by GregorBiswanger** [comment]
Problem was no hybrid support for classic asp.net web apps.
I implement a `HybridSupport.IsElectronActive`-Proptery. See in our sample app in the startup.cs and controllers code, how to use it.
