### ISSUE TITLE
Build failing on OSX

### ISSUE THREAD

**Issue by Jonatthu** [ElectronNET/Electron.NET#99]
I am using this repo 
https://github.com/ElectronNET/electron.net-api-demos

When I run

`dotnet electronize build or dotnet electronize build osx `

The next error message is throw

```
Build Electron Application...

Unhandled Exception: System.AggregateException: One or more errors occurred. (The given key was not present in the dictionary.) ---> System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ElectronNET.CLI.Commands.BuildCommand.<ExecuteAsync>b__13_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ElectronNET.CLI.Program.Main(String[] args)
```

My versions:
Node: 8.9.4
npm: 5.6.0
ElectronNET.CLI Version: 0.0.8.0
dotnet: 2.0.0 and I have tried 2.1.4

**Comment by robertmuehsig** [comment]
Hi - sorry for this issue. We published a newer version with a more "advanced" command line surface. The CLI release is more or less a breaking change and it was supposed to be a pre-release. 

Please try the following:

dotnet electronize build /target osx

With 0.0.8 it is now possible to be more specific for which .NET Core/Electron platform you might build it for. As a example: https://github.com/ElectronNET/Electron.NET/blob/params/buildAll.sh#L28

We will update the master branch shortly and also make sure that we cover this in your documentation.

Sorry!

**Comment by Jonatthu** [comment]
@robertmuehsig That work thanks!

**Comment by robertmuehsig** [comment]
Glad it worked 🤗
